version: '2.0'


services:
  front-end:
    container_name: frontEnd
    image: front-end
    build: .
    ports:
      - '4200:4200'
      - '80:80'
    volumes:
      - './src:/usr/share/docVer/src'
    command: bash -c "ls && node patch.js && ng build && cp nginx.conf /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
